# Generated by Django 3.1.4 on 2021-02-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klausimai',
            options={'verbose_name_plural': 'Klausimai'},
        ),
    ]
