# Generated by Django 3.1.4 on 2021-03-03 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Antraštė')),
                ('title_tag', models.CharField(blank=True, max_length=40, verbose_name='Antraštės trumpinys')),
                ('kategorija', models.CharField(max_length=100, verbose_name='Kategorija')),
                ('operatorius', models.BooleanField(verbose_name='Ar su operatorium ?')),
                ('body', models.TextField(default='Aprašymas', verbose_name='Aprašymas')),
                ('post_date', models.DateField(auto_now_add=True)),
                ('webpuslapis', models.URLField()),
                ('epastas', models.EmailField(blank=True, max_length=254)),
                ('nuotrauka', models.ImageField(blank=True, height_field='image_height', upload_to='technika/', width_field='image_width')),
                ('image_width', models.IntegerField(verbose_name='aukstis')),
                ('image_height', models.IntegerField(verbose_name='plotis')),
                ('kontaktas', models.CharField(max_length=50, verbose_name='Telefonas')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autorius')),
            ],
            options={
                'verbose_name_plural': 'Technika',
            },
        ),
    ]
