# Generated by Django 3.1.4 on 2021-03-04 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technikosnuoma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technika',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='technika',
            name='image_width',
        ),
    ]
