# Generated by Django 3.1.4 on 2021-03-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technikosnuoma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technika',
            name='image_height',
            field=models.IntegerField(blank=True, verbose_name='plotis'),
        ),
        migrations.AlterField(
            model_name='technika',
            name='image_width',
            field=models.IntegerField(blank=True, verbose_name='aukstis'),
        ),
        migrations.AlterField(
            model_name='technika',
            name='webpuslapis',
            field=models.URLField(blank=True),
        ),
    ]
