# Generated by Django 3.1.4 on 2021-03-03 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technikosnuoma', '0003_auto_20210303_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technika',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='technika',
            name='image_width',
        ),
    ]
