# Generated by Django 3.1.4 on 2021-03-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technikosnuoma', '0004_auto_20210303_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technika',
            name='nuotrauka',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
